import { chromium } from '/home/ytani/.npm/_npx/6bcb61ec6d5aea22/node_modules/playwright/index.mjs';
const b = await chromium.launch(); const page = await b.newPage();
const pe = [], ce = [];
page.on('console', m => { if (m.type()==='error') ce.push(m.text()); }); page.on('pageerror', e => pe.push(e.message));
const opts = () => page.evaluate(() => [...document.querySelectorAll('#preset-select optgroup')].filter(g=>/Claude/.test(g.label)).map(g => [g.label, ...[...g.querySelectorAll('option')].map(o => o.value+' | '+o.textContent.trim())]));
await page.goto('http://localhost:8080/', {waitUntil:'domcontentloaded'});
console.log('1a early', JSON.stringify(await opts(), null, 1));
await page.waitForTimeout(5000);
console.log('1b after', JSON.stringify(await opts(), null, 1));
const sel = page.locator('#preset-select');
const info = () => page.evaluate(() => ({title: document.getElementById('article-title')?.textContent, author: document.getElementById('article-author').textContent, head: document.getElementById('text-display').textContent.trim().slice(0,40), full: document.getElementById('text-display').textContent.replace(/\s+/g,'').length}));
console.log('titleEls', await page.evaluate(()=>[...document.querySelectorAll('[id*=title]')].map(e=>e.id+':'+e.textContent.slice(0,40))));
await sel.selectOption('code-ja-0'); await page.waitForTimeout(300);
console.log('2 code-ja-0', JSON.stringify(await info()));
console.log('2 CLAUDE_CODE_JA', JSON.stringify(await page.evaluate(() => typeof CLAUDE_CODE_JA==='undefined' ? 'undef' : {len: CLAUDE_CODE_JA.length, titles: CLAUDE_CODE_JA.map(a=>a.title)})));
await sel.selectOption('claude-summary'); await page.waitForTimeout(300);
console.log('3 summary', JSON.stringify(await page.evaluate(() => { const t=document.getElementById('text-display').textContent; return {len:t.length, hasHaiku: t.includes('Claude Haiku 5.5（claude-haiku-5-5）を追加しました'), hasHaiku2: t.includes('claude-haiku-5-5'), hasCode: t.includes('Claude Code')}; })));
await sel.selectOption('code-ja-0'); await page.waitForTimeout(300);
await page.selectOption('#time-limit-select', '0');
const text = await page.evaluate(() => [...document.querySelectorAll('#text-display .char')].map(e=>e.classList.contains('linebreak')?'':(e.textContent.trim()===''?' ':e.textContent)).join(''));
await page.focus('#typing-input');
for (const ch of text) { if (ch===' ') await page.keyboard.press('Space'); else await page.keyboard.insertText(ch); }
await page.waitForTimeout(800);
console.log('4 text', JSON.stringify(text.slice(0,12)), [...text.slice(5,8)].map(c=>c.charCodeAt(0)), JSON.stringify(await page.evaluate(()=>document.getElementById('typing-input').value)));
console.log('4 progress', await page.evaluate(()=>document.querySelectorAll('#text-display .char.done').length+'/'+document.querySelectorAll('#text-display .char').length));
console.log('4 modal', await page.evaluate(() => document.getElementById('res-modal-title').textContent));
console.log('4 history', JSON.stringify(await page.evaluate(() => { const h=JSON.parse(localStorage.getItem('jp-long-typing-history')); return {n:h.length, last:h[h.length-1]}; })));
console.log('5 pageerrors', pe.length, JSON.stringify(pe), 'consoleErrors', ce.length, JSON.stringify(ce));
await b.close();
