const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch();
  const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
  const errs = []; const dialogs = [];
  p.on('pageerror', e => errs.push(String(e)));
  p.on('dialog', d => { dialogs.push(d.message()); d.dismiss(); });
  await p.route(/^https?:\/\/(?!localhost)/, r => r.abort());
  await p.goto('http://localhost:8080/');
  await p.waitForTimeout(500);
  const ids = ['btn-fetch-news','btn-restart','btn-sound','btn-theme'];
  const read = () => p.evaluate(ids => Object.fromEntries(ids.map(i => { const b = document.getElementById(i); return [i, { svgs: b.querySelectorAll('svg.icon').length, text: b.textContent.trim(), html: b.querySelector('svg').innerHTML }]; })), ids);
  const r1 = await read();
  console.log('1', JSON.stringify(Object.fromEntries(Object.entries(r1).map(([k,v])=>[k,{svgs:v.svgs,text:v.text}]))));
  await p.click('#btn-sound'); const r2 = await read();
  console.log('2 off', r2['btn-sound'].text, r2['btn-sound'].html !== r1['btn-sound'].html);
  await p.click('#btn-sound'); const r2b = await read();
  console.log('2 on', r2b['btn-sound'].text, r2b['btn-sound'].html === r1['btn-sound'].html);
  const col = () => p.evaluate(() => { const b = document.getElementById('btn-theme'); const cs = getComputedStyle(b), s = getComputedStyle(b.querySelector('svg')); return { theme: document.body.dataset.theme || 'dark', btnColor: cs.color, svgColor: s.color, stroke: s.stroke, btnBg: cs.backgroundColor, bodyBg: getComputedStyle(document.body).backgroundColor, html: b.querySelector('svg').innerHTML.slice(0,30) }; });
  const hdr = () => p.locator('header').screenshot({ path: process.env.HOME + '/tmp/playwright-mcp/todo-011-' + 'X.png' });
  const c1 = await col(); console.log('3', JSON.stringify(c1));
  await p.locator('header').screenshot({ path: process.env.HOME + '/tmp/playwright-mcp/todo-011-dark.png' });
  await p.click('#btn-theme'); await p.mouse.move(0,0); await p.waitForTimeout(400);
  const c2 = await col(); console.log('3', JSON.stringify(c2));
  await p.locator('header').screenshot({ path: process.env.HOME + '/tmp/playwright-mcp/todo-011-light.png' });
  console.log('4', await p.evaluate(() => [...document.querySelectorAll('#time-limit-select option')].map(o => o.textContent)));
  const texts = [];
  p.click('#btn-fetch-news');
  await p.waitForTimeout(30); texts.push((await read())['btn-fetch-news'].text);
  await p.waitForFunction(() => document.getElementById('btn-fetch-news').textContent.trim() === 'ニュース更新', null, { timeout: 30000 }).catch(()=>texts.push('TIMEOUT'));
  texts.push((await read())['btn-fetch-news'].text);
  console.log('5', texts, dialogs);
  console.log('6 pageerrors', errs.length, errs);
  await b.close();
})();
